modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

issueTrackerURL="https://github.com/dantaeusb-mc/ZetterGallery/issues"

[[mods]]

modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayURL="https://modrinth.com/mod/zetter-painting-mod"
updateJSONURL="https://api.modrinth.com/updates/ZmLgjf6f/forge_updates.json"
logoFile="zetter-gallery.png"

credits='''
Idea, direction & programming:
* Dmitry Burlakov @dantaeusb

Assets & arts:
* Eliath "Eliathx" Velasco @eliathx
* Sam Pxlsamosa @pxlsamosa
* GrimmNail @grimmnail

Forge Discord:
diesieben07#0714
gigaherz#9173

Examples and references:
Vazkii and Quark team for opening their source code as I often used it as a reference
'''

authors="Dmitry Burlakov <dantaeusb@live.com>"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="zetter"
    mandatory=true
    versionRange="${zetter_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"